{
  inputs,
  pkgs,
  ...
}: {
  nixpkgs.config = {
    allowUnfree = true;
  };

  environment.systemPackages = with pkgs; [
    p7zip
    calc
    gnumake
    fzf
    fd
    ripgrep
    bash-language-server
    lua-language-server
    stylua
    vesktop
    sshfs
    yt-dlp
    elephant # for walker
    lua
    gdk-pixbuf
    ffmpegthumbnailer
    ffmpeg
    libheif.bin
    libheif.out
    webp-pixbuf-loader
    imagemagick
    win2xcur
    btrfs-progs
    kdiskmark
    wlroots
    syncthing
    topiary
    qbittorrent
    gamemode
    evemu
    ydotool
    avfs # i have no idea what it is 
    javaPackages.compiler.openjdk25
    atool
    qtemu
    adwaita-icon-theme
    alsa-utils
    btop-cuda
    clang-tools
    cava
    chafa
    chromium
    curl
    fastfetch
    foot
    git
    heroic
    home-manager
    inkscape-with-extensions
    ipset
    iptables
    libnotify
    nftables
    lutris
    mangohud
    luarocks
    mpv
    nh
    nixd
    nixpkgs-fmt
    alejandra
    obsidian
    osu-lazer-bin
    papirus-icon-theme
    playerctl
    gcc
    plymouth
    prismlauncher
    python313Packages.nvidia-ml-py
    qt5.qtgraphicaleffects
    libsForQt5.qt5.qtgraphicaleffects
    jq
    telegram-desktop
    unzip
    vscode-langservers-extracted
    vulkan-extension-layer
    vulkan-loader
    vulkan-tools
    vulkan-validation-layers
    walker
    wget
    xdg-utils
    xray
    zsh-powerlevel10k
  ];
}
