{
  inputs,
  pkgs,
  ...
}: {
  nixpkgs.config = {
    allowUnfree = true;
  };

  environment.systemPackages = with pkgs; [
    p7zip
    gnumake
    fzf
    fd
    ripgrep
    bash-language-server
    lua-language-server
    vesktop
    sshfs
    yt-dlp
    xorg.xcursorgen
    xcur2png
    imagemagick
    win2xcur
    btrfs-progs
    kdiskmark
    ironbar
    wlroots
    syncthing
    topiary
    qbittorrent
    gamemode
    avfs
    atool
    qtemu
    adwaita-icon-theme
    alsa-utils
    btop-cuda
    clang-tools
    cava
    chafa
    chromium
    clock-rs
    curl
    fastfetch
    foot
    git
    heroic
    home-manager
    inkscape-with-extensions
    ipset
    iptables
    libnotify
    lutris
    mako
    mangohud
    mpv
    nh
    nixd
    nixpkgs-fmt
    alejandra
    nftables
    obsidian
    osu-lazer-bin
    papirus-icon-theme
    playerctl
    gcc
    plymouth
    prismlauncher
    python313Packages.nvidia-ml-py
    qt5.qtgraphicaleffects
    libsForQt5.qt5.qtgraphicaleffects
    ranger
    telegram-desktop
    testdisk
    ueberzugpp
    unzip
    vscode-langservers-extracted
    vulkan-extension-layer
    vulkan-loader
    vulkan-tools
    vulkan-validation-layers
    walker
    wget
    xdg-utils
    xray
    inputs.zen.packages.${pkgs.stdenv.hostPlatform.system}.default
    zsh-powerlevel10k
  ];
}
